"""
LangChain tools for the Agent executor.
Categories: data queries, system operations, content generation,
            external services, code execution (E2B sandbox).
"""
import json
from langchain_core.tools import tool
from app.core.logging import get_logger

logger = get_logger(__name__)


# ── Data Query Tools ──────────────────────────────────────────────────────────

@tool
def query_database(sql: str) -> str:
    """
    Execute a read-only SQL query against the enterprise database.
    Input: a valid SELECT SQL statement.
    Returns: JSON string of query results.
    """
    import sqlalchemy
    from app.core.config import get_settings
    settings = get_settings()
    # Use synchronous connection for tool execution
    sync_url = settings.database_url  # postgresql://...
    engine = sqlalchemy.create_engine(sync_url)
    try:
        with engine.connect() as conn:
            result = conn.execute(sqlalchemy.text(sql))
            rows = [dict(r._mapping) for r in result]
            return json.dumps(rows, ensure_ascii=False, default=str)
    except Exception as e:
        return json.dumps({"error": str(e)})
    finally:
        engine.dispose()


@tool
def search_knowledge(query: str) -> str:
    """
    Search the enterprise knowledge base for relevant information.
    Input: a natural language query.
    Returns: top matching document excerpts.
    """
    # This is a sync wrapper; the full async RAG pipeline is used directly in the graph
    return f"[Knowledge search for: {query}] — use RAG pipeline node for full retrieval."


# ── System Operation Tools ────────────────────────────────────────────────────

@tool
def create_ticket(title: str, description: str, priority: str = "medium") -> str:
    """
    Create a support or task ticket in the enterprise ticketing system.
    priority: low | medium | high | urgent
    Returns: ticket ID and status.
    """
    import uuid
    ticket_id = f"TKT-{uuid.uuid4().hex[:8].upper()}"
    logger.info("Ticket created", ticket_id=ticket_id, title=title, priority=priority)
    return json.dumps({
        "ticket_id": ticket_id,
        "title": title,
        "status": "created",
        "priority": priority,
    })


@tool
def call_internal_api(endpoint: str, method: str = "GET", payload: str = "{}") -> str:
    """
    Call an internal enterprise API endpoint.
    endpoint: relative path, e.g. /api/hr/employees
    method: GET | POST | PUT
    payload: JSON string body (for POST/PUT)
    Returns: API response as JSON string.
    """
    import httpx
    from app.core.config import get_settings
    # In production, base_url would be the internal API gateway
    base_url = "http://internal-api:8080"
    try:
        data = json.loads(payload)
        with httpx.Client(timeout=10) as client:
            if method.upper() == "GET":
                resp = client.get(f"{base_url}{endpoint}")
            elif method.upper() == "POST":
                resp = client.post(f"{base_url}{endpoint}", json=data)
            else:
                resp = client.put(f"{base_url}{endpoint}", json=data)
        return resp.text
    except Exception as e:
        return json.dumps({"error": str(e)})


# ── Content Generation Tools ──────────────────────────────────────────────────

@tool
def generate_report(title: str, data: str, report_type: str = "summary") -> str:
    """
    Generate a structured report from provided data.
    data: JSON string of data points.
    report_type: summary | comparison | trend
    Returns: Markdown-formatted report.
    """
    try:
        parsed = json.loads(data)
    except Exception:
        parsed = data

    report = f"# {title}\n\n"
    report += f"**Report Type:** {report_type}\n\n"
    report += "## Data\n\n"
    if isinstance(parsed, list):
        for item in parsed:
            report += f"- {item}\n"
    else:
        report += f"```json\n{json.dumps(parsed, ensure_ascii=False, indent=2)}\n```\n"
    report += "\n_Generated by Enterprise Brain_"
    return report


@tool
def send_email(to: str, subject: str, body: str) -> str:
    """
    Send an email via the enterprise email system.
    to: recipient email address
    Returns: send status.
    """
    logger.info("Email sent (stub)", to=to, subject=subject)
    # Production: integrate with SMTP / Exchange / DingTalk mail
    return json.dumps({"status": "sent", "to": to, "subject": subject})


# ── External Service Tools ────────────────────────────────────────────────────

@tool
def web_search(query: str) -> str:
    """
    Search the public web for current information.
    Returns: top search result snippets.
    """
    try:
        from langchain_community.tools import DuckDuckGoSearchRun
        search = DuckDuckGoSearchRun()
        return search.run(query)
    except Exception as e:
        return json.dumps({"error": str(e)})


# ── Code Execution Tool (E2B Sandbox) ─────────────────────────────────────────

@tool
def execute_python_code(code: str) -> str:
    """
    Execute Python code in a secure cloud sandbox (E2B).
    Use for: data analysis, chart generation, calculations.
    Returns: stdout output and any generated file paths.
    """
    from app.core.config import get_settings
    settings = get_settings()
    try:
        from e2b_code_interpreter import Sandbox
        with Sandbox(api_key=settings.e2b_api_key) as sandbox:
            result = sandbox.run_code(code)
            output = "\n".join(str(l) for l in result.logs.stdout)
            errors = "\n".join(str(l) for l in result.logs.stderr)
            return json.dumps({
                "output": output,
                "errors": errors if errors else None,
            })
    except Exception as e:
        return json.dumps({"error": str(e)})


# ── Tool registry ─────────────────────────────────────────────────────────────

ALL_TOOLS = [
    query_database,
    search_knowledge,
    create_ticket,
    call_internal_api,
    generate_report,
    send_email,
    web_search,
    execute_python_code,
]
